context.lineWidth = 2;
Utils.drawLine(x, y, x + 15, y + 15)
Utils.drawLine(x, y, x - 15, y - 15)
Utils.drawLine(x, y, x + 15, y - 15)
Utils.drawLine(x, y, x - 15, y + 15)
Utils.drawLine(x, y, x, y - 20)
Utils.drawLine(x, y, x - 20, y)
Utils.drawLine(x, y, x, y + 20)
Utils.drawLine(x, y, x + 20, y)
Utils.drawLine(x, y, x + 14, y - 6)
Utils.drawLine(x, y, x - 14, y - 6)
Utils.drawLine(x, y, x + 14, y + 6)
Utils.drawLine(x, y, x - 14, y - 6)
Utils.drawLine(x, y, x - 14, y + 6)
Utils.drawLine(x, y, x + 6, y - 14)
Utils.drawLine(x, y, x - 6, y - 14)
Utils.drawLine(x, y, x + 6, y + 14)
Utils.drawLine(x, y, x - 6, y - 14)
Utils.drawLine(x, y, x - 6, y + 14)